### ISSUE TITLE
only temperature sensor appears

### ISSUE THREAD

**Issue by neattrick** [jerome-gr/intuis#17]
### System Health details

Core
2023.11.3
Supervisor
2023.11.3
Operating System
Interface utilisateur
20231030.2

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/jerome-gr/intuis/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I successfully integrated the component but only the temperature sensor appears

### Reproduction steps

1. integrate the component
2. log in OK
3.adding my radiator
4. only temperature sensor appears. impossible to switch off or on the device.
...

### Debug logs

```text
i'm available for any further details needed to help
```

**Comment by neattrick** [comment]
Maybe do i have to modify the client id and secret set in the const.py file ?
How did you generate them ?

**Comment by jerome-gr** [comment]
Hi @neattrick 

Thanks for your feedback!

The integration is still a work in progress and for now there's only the temp sensor available. 
I need to work on adding the on/off feature but I have no time to do it at the moment :(

**Comment by neattrick** [comment]
No problem. I'm not a "real" developer but if i can help you for testing, it would be a pleasure !

**Comment by neattrick** [comment]
May you share me where you found the api documentation that i could check and see if i can help you to make progress the dev of the component ?

**Comment by jerome-gr** [comment]
Hi @neattrick 

Sorry for the response delay

I no longer own these radiators so I think I'll archive this repository. 

As Intuis (ex Intuiv-Muller) use Netatmo, I follow the API of the netatmo integration in the [home assistant core repo](https://github.com/home-assistant/core/tree/dev/homeassistant/components/netatmo) and the [jeedom integration](https://github.com/shun84/jeedom-plugin-mullerintuitiv).
Hope this helps :)
